include (${CMAKE_SOURCE_DIR}/cmake/argument_macros.cmake)

function(fftw_gen_simd_dummy)
  set(_keywords "NAME" "HEADER" "ORIGDIR" "DESTDIR")
  unset(_dummy_gen_orig_directory)
  unset(_dummy_gen_dest_directory)
  unset(_dummy_gen_name)
  unset(_dummy_gen_header)
  unset(_lastkeyword)
  foreach(arg IN LISTS ARGN)
    if(arg IN_LIST _keywords)
      set(_lastkeyword ${arg})
      continue()
    elseif(_lastkeyword STREQUAL "ORIGDIR")
      arg_check_and_set(_dummy_gen_orig_directory ${arg} ORIGDIR)
    elseif(_lastkeyword STREQUAL "DESTDIR")
      arg_check_and_set(_dummy_gen_dest_directory ${arg} DESTDIR)
    elseif(_lastkeyword STREQUAL "NAME")
      arg_check_and_set(_dummy_gen_name ${arg} NAME)
    elseif(_lastkeyword STREQUAL "HEADER")
      arg_check_and_set(_dummy_gen_header ${arg} HEADER)
    endif()
  endforeach()
  arg_require_set(_dummy_gen_header HEADER)
  arg_require_set(_dummy_gen_name NAME)
  arg_require_set(_dummy_gen_dest_directory DESTDIR)
  arg_require_set(_dummy_gen_orig_directory ORIGDIR)

  file(RELATIVE_PATH _dummy_relative_path ${_dummy_gen_dest_directory} ${_dummy_gen_orig_directory}/${_dummy_gen_name})

  unset(_dummy_gen_file_content)
  string(TIMESTAMP _dummy_gen_cur_time "%Y-%m-%d %H:%MZ"  UTC)
  string(APPEND _dummy_gen_file_content "/* Generated automatically on ${_dummy_gen_cur_time}*/\n/* --> DO NOT EDIT! <-- */\n")
  string(APPEND _dummy_gen_file_content "#define SIMD_HEADER \"${_dummy_gen_header}\"\n")
  string(APPEND _dummy_gen_file_content "#include \"${_dummy_relative_path}\"\n")

  file(GENERATE OUTPUT "${_dummy_gen_dest_directory}/${_dummy_gen_name}"
       CONTENT  ${_dummy_gen_file_content})

endfunction()
