/* Generated by: ../../genfft/gen_twiddle_c -standalone -fma -reorder-insns -simd -compact -variables 100000 -include fftw-spu.h -trivial-stores -n 3 -name X(spu_t1fv_3) */

/*
 * This function contains 8 FP additions, 8 FP multiplications,
 * (or, 5 additions, 5 multiplications, 3 fused multiply/add),
 * 15 stack variables, and 6 memory accesses
 */
/*
 * Generator Id's : 
 * $Id: algsimp.ml,v 1.9 2006-02-12 23:34:12 athena Exp $
 * $Id: fft.ml,v 1.4 2006-01-05 03:04:27 stevenj Exp $
 * $Id: gen_twiddle_c.ml,v 1.14 2006-02-12 23:34:12 athena Exp $
 */

#include "fftw-spu.h"

const R *X(spu_t1fv_3) (R *ri, R *ii, const R *W, stride ios, INT m, INT dist) {
     DVK(KP500000000, +0.500000000000000000000000000000000000000000000);
     DVK(KP866025403, +0.866025403784438646763723170752936183471402627);
     INT i;
     R *x;
     x = ri;
     for (i = m; i > 0; i = i - VL, x = x + (VL * dist), W = W + (TWVL * 4), MAKE_VOLATILE_STRIDE(ios)) {
	  V T1, T6, T9, T3, T5, T2, T4, T8, T7, Tb, Ta;
	  T1 = LD(&(x[0]), dist, &(x[0]));
	  T2 = LD(&(x[WS(ios, 1)]), dist, &(x[WS(ios, 1)]));
	  T3 = BYTWJ(&(W[0]), T2);
	  T4 = LD(&(x[WS(ios, 2)]), dist, &(x[0]));
	  T5 = BYTWJ(&(W[TWVL * 2]), T4);
	  T6 = VADD(T3, T5);
	  T9 = VMUL(LDK(KP866025403), VSUB(T5, T3));
	  T7 = VADD(T1, T6);
	  T8 = VFNMS(LDK(KP500000000), T6, T1);
	  ST(&(x[0]), T7, dist, &(x[0]));
	  Tb = VFMAI(T9, T8);
	  Ta = VFNMSI(T9, T8);
	  ST(&(x[WS(ios, 2)]), Ta, dist, &(x[0]));
	  ST(&(x[WS(ios, 1)]), Tb, dist, &(x[WS(ios, 1)]));
     }
     return W;
}
