/* Generated by: ../../genfft/gen_twiddle_c -standalone -fma -reorder-insns -simd -compact -variables 100000 -include fftw-spu.h -trivial-stores -n 15 -name X(spu_t1fv_15) */

/*
 * This function contains 92 FP additions, 77 FP multiplications,
 * (or, 50 additions, 35 multiplications, 42 fused multiply/add),
 * 117 stack variables, and 30 memory accesses
 */
/*
 * Generator Id's : 
 * $Id: algsimp.ml,v 1.9 2006-02-12 23:34:12 athena Exp $
 * $Id: fft.ml,v 1.4 2006-01-05 03:04:27 stevenj Exp $
 * $Id: gen_twiddle_c.ml,v 1.14 2006-02-12 23:34:12 athena Exp $
 */

#include "fftw-spu.h"

const R *X(spu_t1fv_15) (R *ri, R *ii, const R *W, stride ios, INT m, INT dist) {
     DVK(KP823639103, +0.823639103546331925877420039278190003029660514);
     DVK(KP910592997, +0.910592997310029334643087372129977886038870291);
     DVK(KP559016994, +0.559016994374947424102293417182819058860154590);
     DVK(KP618033988, +0.618033988749894848204586834365638117720309180);
     DVK(KP951056516, +0.951056516295153572116439333379382143405698634);
     DVK(KP866025403, +0.866025403784438646763723170752936183471402627);
     DVK(KP250000000, +0.250000000000000000000000000000000000000000000);
     DVK(KP500000000, +0.500000000000000000000000000000000000000000000);
     INT i;
     R *x;
     x = ri;
     for (i = m; i > 0; i = i - VL, x = x + (VL * dist), W = W + (TWVL * 28), MAKE_VOLATILE_STRIDE(ios)) {
	  V T1g, T7, TU, T17, T1a, To, TL, TK, TF, T1j, T1l, T1d, T1e, T11, T13;
	  V T1, T5, T3, T4, T2, T6, T9, Tq, Ty, Th, Te, T15, Tv, T18, TD;
	  V T19, Tm, T16, T8, Tp, Tx, Tg, Tb, Td, Ta, Tc, Ts, Tu, Tr, Tt;
	  V TA, TC, Tz, TB, Tj, Tl, Ti, Tk, T1h, T1i, TV, TW, Tf, Tn, TY;
	  V TZ, Tw, TE, TX, T10, T12, T1k, T1J, T1I, T1G, T1H, TQ, TM, TT, TJ;
	  V TP, TI, TH, TG, TR, TS, TO, TN, T1r, T1n, T1D, T1z, T1q, T1c, T1C;
	  V T1w, T1f, T1x, T1y, T1m, T1v, T1b, T1u, T14, T1p, T1F, T1o, T1E, T1t, T1B;
	  V T1s, T1A;
	  T1 = LD(&(x[0]), dist, &(x[0]));
	  T4 = LD(&(x[WS(ios, 10)]), dist, &(x[0]));
	  T5 = BYTWJ(&(W[TWVL * 18]), T4);
	  T2 = LD(&(x[WS(ios, 5)]), dist, &(x[WS(ios, 1)]));
	  T3 = BYTWJ(&(W[TWVL * 8]), T2);
	  T1g = VSUB(T5, T3);
	  T6 = VADD(T3, T5);
	  T7 = VADD(T1, T6);
	  TU = VFNMS(LDK(KP500000000), T6, T1);
	  T8 = LD(&(x[WS(ios, 3)]), dist, &(x[WS(ios, 1)]));
	  T9 = BYTWJ(&(W[TWVL * 4]), T8);
	  Tp = LD(&(x[WS(ios, 6)]), dist, &(x[0]));
	  Tq = BYTWJ(&(W[TWVL * 10]), Tp);
	  Tx = LD(&(x[WS(ios, 9)]), dist, &(x[WS(ios, 1)]));
	  Ty = BYTWJ(&(W[TWVL * 16]), Tx);
	  Tg = LD(&(x[WS(ios, 12)]), dist, &(x[0]));
	  Th = BYTWJ(&(W[TWVL * 22]), Tg);
	  Ta = LD(&(x[WS(ios, 8)]), dist, &(x[0]));
	  Tb = BYTWJ(&(W[TWVL * 14]), Ta);
	  Tc = LD(&(x[WS(ios, 13)]), dist, &(x[WS(ios, 1)]));
	  Td = BYTWJ(&(W[TWVL * 24]), Tc);
	  Te = VADD(Tb, Td);
	  T15 = VSUB(Td, Tb);
	  Tr = LD(&(x[WS(ios, 11)]), dist, &(x[WS(ios, 1)]));
	  Ts = BYTWJ(&(W[TWVL * 20]), Tr);
	  Tt = LD(&(x[WS(ios, 1)]), dist, &(x[WS(ios, 1)]));
	  Tu = BYTWJ(&(W[0]), Tt);
	  Tv = VADD(Ts, Tu);
	  T18 = VSUB(Tu, Ts);
	  Tz = LD(&(x[WS(ios, 14)]), dist, &(x[0]));
	  TA = BYTWJ(&(W[TWVL * 26]), Tz);
	  TB = LD(&(x[WS(ios, 4)]), dist, &(x[0]));
	  TC = BYTWJ(&(W[TWVL * 6]), TB);
	  TD = VADD(TA, TC);
	  T19 = VSUB(TC, TA);
	  Ti = LD(&(x[WS(ios, 2)]), dist, &(x[0]));
	  Tj = BYTWJ(&(W[TWVL * 2]), Ti);
	  Tk = LD(&(x[WS(ios, 7)]), dist, &(x[WS(ios, 1)]));
	  Tl = BYTWJ(&(W[TWVL * 12]), Tk);
	  Tm = VADD(Tj, Tl);
	  T16 = VSUB(Tl, Tj);
	  T17 = VSUB(T15, T16);
	  T1h = VADD(T15, T16);
	  T1i = VADD(T18, T19);
	  T1a = VSUB(T18, T19);
	  Tf = VADD(T9, Te);
	  TV = VFNMS(LDK(KP500000000), Te, T9);
	  TW = VFNMS(LDK(KP500000000), Tm, Th);
	  Tn = VADD(Th, Tm);
	  To = VADD(Tf, Tn);
	  TL = VSUB(Tf, Tn);
	  TY = VFNMS(LDK(KP500000000), Tv, Tq);
	  Tw = VADD(Tq, Tv);
	  TE = VADD(Ty, TD);
	  TZ = VFNMS(LDK(KP500000000), TD, Ty);
	  TK = VSUB(Tw, TE);
	  TF = VADD(Tw, TE);
	  T1j = VADD(T1h, T1i);
	  T1l = VSUB(T1h, T1i);
	  TX = VADD(TV, TW);
	  T1d = VSUB(TV, TW);
	  T1e = VSUB(TY, TZ);
	  T10 = VADD(TY, TZ);
	  T11 = VADD(TX, T10);
	  T13 = VSUB(TX, T10);
	  T12 = VFNMS(LDK(KP250000000), T11, TU);
	  T1G = VADD(TU, T11);
	  T1H = VMUL(LDK(KP866025403), VADD(T1g, T1j));
	  T1k = VFNMS(LDK(KP250000000), T1j, T1g);
	  T1J = VFMAI(T1H, T1G);
	  T1I = VFNMSI(T1H, T1G);
	  ST(&(x[WS(ios, 5)]), T1I, dist, &(x[WS(ios, 1)]));
	  ST(&(x[WS(ios, 10)]), T1J, dist, &(x[0]));
	  TQ = VMUL(LDK(KP951056516), VFMA(LDK(KP618033988), TK, TL));
	  TM = VMUL(LDK(KP951056516), VFNMS(LDK(KP618033988), TL, TK));
	  TG = VADD(To, TF);
	  TI = VSUB(To, TF);
	  TT = VADD(T7, TG);
	  TH = VFNMS(LDK(KP250000000), TG, T7);
	  TJ = VFNMS(LDK(KP559016994), TI, TH);
	  TP = VFMA(LDK(KP559016994), TI, TH);
	  ST(&(x[0]), TT, dist, &(x[0]));
	  TS = VFMAI(TQ, TP);
	  TR = VFNMSI(TQ, TP);
	  ST(&(x[WS(ios, 9)]), TS, dist, &(x[WS(ios, 1)]));
	  TN = VFNMSI(TM, TJ);
	  TO = VFMAI(TM, TJ);
	  ST(&(x[WS(ios, 3)]), TN, dist, &(x[WS(ios, 1)]));
	  ST(&(x[WS(ios, 12)]), TO, dist, &(x[0]));
	  ST(&(x[WS(ios, 6)]), TR, dist, &(x[0]));
	  T1f = VFMA(LDK(KP618033988), T1e, T1d);
	  T1x = VFNMS(LDK(KP618033988), T1d, T1e);
	  T1y = VFNMS(LDK(KP559016994), T1l, T1k);
	  T1m = VFMA(LDK(KP559016994), T1l, T1k);
	  T1r = VMUL(LDK(KP951056516), VFMA(LDK(KP910592997), T1m, T1f));
	  T1n = VMUL(LDK(KP951056516), VFNMS(LDK(KP910592997), T1m, T1f));
	  T1D = VMUL(LDK(KP951056516), VFMA(LDK(KP910592997), T1y, T1x));
	  T1z = VMUL(LDK(KP951056516), VFNMS(LDK(KP910592997), T1y, T1x));
	  T1v = VFNMS(LDK(KP618033988), T17, T1a);
	  T1b = VFMA(LDK(KP618033988), T1a, T17);
	  T1u = VFNMS(LDK(KP559016994), T13, T12);
	  T14 = VFMA(LDK(KP559016994), T13, T12);
	  T1q = VFNMS(LDK(KP823639103), T1b, T14);
	  T1c = VFMA(LDK(KP823639103), T1b, T14);
	  T1C = VFNMS(LDK(KP823639103), T1v, T1u);
	  T1w = VFMA(LDK(KP823639103), T1v, T1u);
	  T1p = VFMAI(T1n, T1c);
	  T1o = VFNMSI(T1n, T1c);
	  ST(&(x[WS(ios, 1)]), T1o, dist, &(x[WS(ios, 1)]));
	  T1F = VFMAI(T1D, T1C);
	  T1E = VFNMSI(T1D, T1C);
	  ST(&(x[WS(ios, 8)]), T1E, dist, &(x[0]));
	  ST(&(x[WS(ios, 7)]), T1F, dist, &(x[WS(ios, 1)]));
	  ST(&(x[WS(ios, 14)]), T1p, dist, &(x[0]));
	  T1t = VFMAI(T1r, T1q);
	  T1s = VFNMSI(T1r, T1q);
	  ST(&(x[WS(ios, 11)]), T1s, dist, &(x[WS(ios, 1)]));
	  T1B = VFMAI(T1z, T1w);
	  T1A = VFNMSI(T1z, T1w);
	  ST(&(x[WS(ios, 13)]), T1A, dist, &(x[WS(ios, 1)]));
	  ST(&(x[WS(ios, 2)]), T1B, dist, &(x[0]));
	  ST(&(x[WS(ios, 4)]), T1t, dist, &(x[0]));
     }
     return W;
}
