/* Generated by: ../../genfft/gen_twiddle_c -standalone -fma -reorder-insns -simd -compact -variables 100000 -include fftw-spu.h -trivial-stores -n 10 -name X(spu_t1fv_10) */

/*
 * This function contains 51 FP additions, 40 FP multiplications,
 * (or, 33 additions, 22 multiplications, 18 fused multiply/add),
 * 67 stack variables, and 20 memory accesses
 */
/*
 * Generator Id's : 
 * $Id: algsimp.ml,v 1.9 2006-02-12 23:34:12 athena Exp $
 * $Id: fft.ml,v 1.4 2006-01-05 03:04:27 stevenj Exp $
 * $Id: gen_twiddle_c.ml,v 1.14 2006-02-12 23:34:12 athena Exp $
 */

#include "fftw-spu.h"

const R *X(spu_t1fv_10) (R *ri, R *ii, const R *W, stride ios, INT m, INT dist) {
     DVK(KP559016994, +0.559016994374947424102293417182819058860154590);
     DVK(KP618033988, +0.618033988749894848204586834365638117720309180);
     DVK(KP951056516, +0.951056516295153572116439333379382143405698634);
     DVK(KP250000000, +0.250000000000000000000000000000000000000000000);
     INT i;
     R *x;
     x = ri;
     for (i = m; i > 0; i = i - VL, x = x + (VL * dist), W = W + (TWVL * 18), MAKE_VOLATILE_STRIDE(ios)) {
	  V T4, TF, Tv, Tw, TR, TQ, TM, TO, Tt, Tr, T1, T3, T2, T9, TG;
	  V Tp, TK, Te, TH, Tk, TJ, T6, T8, T5, T7, Tm, To, Tl, Tn, Tb;
	  V Td, Ta, Tc, Th, Tj, Tg, Ti, Tf, Tq, TI, TL, Ts, TN, TE, TZ;
	  V Tx, TB, Tu, TA, Tz, TC, Ty, TD, TS, TW, TP, TV, TU, TX, TT;
	  V TY;
	  T1 = LD(&(x[0]), dist, &(x[0]));
	  T2 = LD(&(x[WS(ios, 5)]), dist, &(x[WS(ios, 1)]));
	  T3 = BYTWJ(&(W[TWVL * 8]), T2);
	  T4 = VSUB(T1, T3);
	  TF = VADD(T1, T3);
	  T5 = LD(&(x[WS(ios, 2)]), dist, &(x[0]));
	  T6 = BYTWJ(&(W[TWVL * 2]), T5);
	  T7 = LD(&(x[WS(ios, 7)]), dist, &(x[WS(ios, 1)]));
	  T8 = BYTWJ(&(W[TWVL * 12]), T7);
	  T9 = VSUB(T6, T8);
	  TG = VADD(T6, T8);
	  Tl = LD(&(x[WS(ios, 6)]), dist, &(x[0]));
	  Tm = BYTWJ(&(W[TWVL * 10]), Tl);
	  Tn = LD(&(x[WS(ios, 1)]), dist, &(x[WS(ios, 1)]));
	  To = BYTWJ(&(W[0]), Tn);
	  Tp = VSUB(Tm, To);
	  TK = VADD(Tm, To);
	  Ta = LD(&(x[WS(ios, 8)]), dist, &(x[0]));
	  Tb = BYTWJ(&(W[TWVL * 14]), Ta);
	  Tc = LD(&(x[WS(ios, 3)]), dist, &(x[WS(ios, 1)]));
	  Td = BYTWJ(&(W[TWVL * 4]), Tc);
	  Te = VSUB(Tb, Td);
	  TH = VADD(Tb, Td);
	  Tg = LD(&(x[WS(ios, 4)]), dist, &(x[0]));
	  Th = BYTWJ(&(W[TWVL * 6]), Tg);
	  Ti = LD(&(x[WS(ios, 9)]), dist, &(x[WS(ios, 1)]));
	  Tj = BYTWJ(&(W[TWVL * 16]), Ti);
	  Tk = VSUB(Th, Tj);
	  TJ = VADD(Th, Tj);
	  Tv = VSUB(T9, Te);
	  Tf = VADD(T9, Te);
	  Tq = VADD(Tk, Tp);
	  Tw = VSUB(Tk, Tp);
	  TR = VSUB(TG, TH);
	  TI = VADD(TG, TH);
	  TL = VADD(TJ, TK);
	  TQ = VSUB(TJ, TK);
	  TM = VADD(TI, TL);
	  TO = VSUB(TI, TL);
	  Tt = VSUB(Tf, Tq);
	  Tr = VADD(Tf, Tq);
	  TE = VADD(T4, Tr);
	  Ts = VFNMS(LDK(KP250000000), Tr, T4);
	  ST(&(x[WS(ios, 5)]), TE, dist, &(x[WS(ios, 1)]));
	  TZ = VADD(TF, TM);
	  TN = VFNMS(LDK(KP250000000), TM, TF);
	  ST(&(x[0]), TZ, dist, &(x[0]));
	  Tx = VMUL(LDK(KP951056516), VFMA(LDK(KP618033988), Tw, Tv));
	  TB = VMUL(LDK(KP951056516), VFNMS(LDK(KP618033988), Tv, Tw));
	  Tu = VFMA(LDK(KP559016994), Tt, Ts);
	  TA = VFNMS(LDK(KP559016994), Tt, Ts);
	  Ty = VFNMSI(Tx, Tu);
	  Tz = VFMAI(Tx, Tu);
	  ST(&(x[WS(ios, 1)]), Ty, dist, &(x[WS(ios, 1)]));
	  TD = VFMAI(TB, TA);
	  TC = VFNMSI(TB, TA);
	  ST(&(x[WS(ios, 7)]), TD, dist, &(x[WS(ios, 1)]));
	  ST(&(x[WS(ios, 9)]), Tz, dist, &(x[WS(ios, 1)]));
	  ST(&(x[WS(ios, 3)]), TC, dist, &(x[WS(ios, 1)]));
	  TS = VMUL(LDK(KP951056516), VFNMS(LDK(KP618033988), TR, TQ));
	  TW = VMUL(LDK(KP951056516), VFMA(LDK(KP618033988), TQ, TR));
	  TP = VFNMS(LDK(KP559016994), TO, TN);
	  TV = VFMA(LDK(KP559016994), TO, TN);
	  TT = VFMAI(TS, TP);
	  TU = VFNMSI(TS, TP);
	  ST(&(x[WS(ios, 2)]), TT, dist, &(x[0]));
	  TY = VFNMSI(TW, TV);
	  TX = VFMAI(TW, TV);
	  ST(&(x[WS(ios, 6)]), TY, dist, &(x[0]));
	  ST(&(x[WS(ios, 8)]), TU, dist, &(x[0]));
	  ST(&(x[WS(ios, 4)]), TX, dist, &(x[0]));
     }
     return W;
}
