/* Generated by: ../../genfft/gen_twiddle_c -standalone -fma -reorder-insns -simd -compact -variables 100000 -include fftw-spu.h -trivial-stores -n 4 -name X(spu_t1fv_4) */

/*
 * This function contains 11 FP additions, 8 FP multiplications,
 * (or, 9 additions, 6 multiplications, 2 fused multiply/add),
 * 17 stack variables, and 8 memory accesses
 */
/*
 * Generator Id's : 
 * $Id: algsimp.ml,v 1.9 2006-02-12 23:34:12 athena Exp $
 * $Id: fft.ml,v 1.4 2006-01-05 03:04:27 stevenj Exp $
 * $Id: gen_twiddle_c.ml,v 1.14 2006-02-12 23:34:12 athena Exp $
 */

#include "fftw-spu.h"

const R *X(spu_t1fv_4) (R *ri, R *ii, const R *W, stride ios, INT m, INT dist) {
     INT i;
     R *x;
     x = ri;
     for (i = m; i > 0; i = i - VL, x = x + (VL * dist), W = W + (TWVL * 6), MAKE_VOLATILE_STRIDE(ios)) {
	  V T4, Tc, T9, Td, T1, T3, T2, T6, T8, T5, T7, Tb, Te, Ta, Tf;
	  T1 = LD(&(x[0]), dist, &(x[0]));
	  T2 = LD(&(x[WS(ios, 2)]), dist, &(x[0]));
	  T3 = BYTWJ(&(W[TWVL * 2]), T2);
	  T4 = VSUB(T1, T3);
	  Tc = VADD(T1, T3);
	  T5 = LD(&(x[WS(ios, 1)]), dist, &(x[WS(ios, 1)]));
	  T6 = BYTWJ(&(W[0]), T5);
	  T7 = LD(&(x[WS(ios, 3)]), dist, &(x[WS(ios, 1)]));
	  T8 = BYTWJ(&(W[TWVL * 4]), T7);
	  T9 = VSUB(T6, T8);
	  Td = VADD(T6, T8);
	  Ta = VFNMSI(T9, T4);
	  Tb = VFMAI(T9, T4);
	  ST(&(x[WS(ios, 1)]), Ta, dist, &(x[WS(ios, 1)]));
	  Tf = VADD(Tc, Td);
	  Te = VSUB(Tc, Td);
	  ST(&(x[0]), Tf, dist, &(x[0]));
	  ST(&(x[WS(ios, 3)]), Tb, dist, &(x[WS(ios, 1)]));
	  ST(&(x[WS(ios, 2)]), Te, dist, &(x[0]));
     }
     return W;
}
