/* Generated by: ../../genfft/gen_notw_c -standalone -fma -reorder-insns -simd -compact -variables 100000 -with-ostride 2 -include fftw-spu.h -store-multiple 2 -n 8 -name X(spu_n2fv_8) */

/*
 * This function contains 26 FP additions, 10 FP multiplications,
 * (or, 16 additions, 0 multiplications, 10 fused multiply/add),
 * 38 stack variables, and 20 memory accesses
 */
/*
 * Generator Id's : 
 * $Id: algsimp.ml,v 1.9 2006-02-12 23:34:12 athena Exp $
 * $Id: fft.ml,v 1.4 2006-01-05 03:04:27 stevenj Exp $
 * $Id: gen_notw_c.ml,v 1.17 2006-02-12 23:34:12 athena Exp $
 */

#include "fftw-spu.h"

void X(spu_n2fv_8) (const R *ri, const R *ii, R *ro, R *io, stride is, stride os, INT v, INT ivs, INT ovs) {
     DVK(KP707106781, +0.707106781186547524400844362104849039284835938);
     INT i;
     const R *xi;
     R *xo;
     xi = ri;
     xo = ro;
     for (i = v; i > 0; i = i - VL, xi = xi + (VL * ivs), xo = xo + (VL * ovs), MAKE_VOLATILE_STRIDE(is), MAKE_VOLATILE_STRIDE(os)) {
	  V Tj, T3, Tk, Te, Tm, Tn, Tf, Ta, T1, T2, Tc, Td, T6, T9, T4;
	  V T5, T7, T8, Th, Ti, Tr, Tl, To, Tu, Ts, Tb, Tg, Tp, Tq, Tt;
	  V Tv, Tw, Tx, Ty;
	  T1 = LD(&(xi[0]), ivs, &(xi[0]));
	  T2 = LD(&(xi[WS(is, 4)]), ivs, &(xi[0]));
	  Tj = VADD(T1, T2);
	  T3 = VSUB(T1, T2);
	  Tc = LD(&(xi[WS(is, 2)]), ivs, &(xi[0]));
	  Td = LD(&(xi[WS(is, 6)]), ivs, &(xi[0]));
	  Tk = VADD(Tc, Td);
	  Te = VSUB(Tc, Td);
	  T4 = LD(&(xi[WS(is, 1)]), ivs, &(xi[WS(is, 1)]));
	  T5 = LD(&(xi[WS(is, 5)]), ivs, &(xi[WS(is, 1)]));
	  Tm = VADD(T4, T5);
	  T6 = VSUB(T4, T5);
	  T7 = LD(&(xi[WS(is, 7)]), ivs, &(xi[WS(is, 1)]));
	  T8 = LD(&(xi[WS(is, 3)]), ivs, &(xi[WS(is, 1)]));
	  T9 = VSUB(T7, T8);
	  Tn = VADD(T7, T8);
	  Tf = VSUB(T9, T6);
	  Ta = VADD(T6, T9);
	  Th = VFNMS(LDK(KP707106781), Ta, T3);
	  Tb = VFMA(LDK(KP707106781), Ta, T3);
	  Tg = VFNMS(LDK(KP707106781), Tf, Te);
	  Ti = VFMA(LDK(KP707106781), Tf, Te);
	  Tr = VFNMSI(Tg, Tb);
	  STM2(&(xo[2]), Tr, ovs, &(xo[2]));
	  Ts = VFMAI(Tg, Tb);
	  STM2(&(xo[14]), Ts, ovs, &(xo[2]));
	  Tl = VADD(Tj, Tk);
	  Tp = VSUB(Tj, Tk);
	  Tq = VSUB(Tn, Tm);
	  To = VADD(Tm, Tn);
	  Tt = VFNMSI(Tq, Tp);
	  STM2(&(xo[12]), Tt, ovs, &(xo[0]));
	  STN2(&(xo[12]), Tt, Ts, ovs);
	  Tu = VFMAI(Tq, Tp);
	  STM2(&(xo[4]), Tu, ovs, &(xo[0]));
	  Tv = VFNMSI(Ti, Th);
	  STM2(&(xo[10]), Tv, ovs, &(xo[2]));
	  Tw = VFMAI(Ti, Th);
	  STM2(&(xo[6]), Tw, ovs, &(xo[2]));
	  STN2(&(xo[4]), Tu, Tw, ovs);
	  Tx = VSUB(Tl, To);
	  STM2(&(xo[8]), Tx, ovs, &(xo[0]));
	  STN2(&(xo[8]), Tx, Tv, ovs);
	  Ty = VADD(Tl, To);
	  STM2(&(xo[0]), Ty, ovs, &(xo[0]));
	  STN2(&(xo[0]), Ty, Tr, ovs);
     }
}
