/* Generated by: ../../genfft/gen_twiddle_c -standalone -fma -reorder-insns -simd -compact -variables 100000 -include fftw-spu.h -trivial-stores -n 7 -name X(spu_t1fv_7) */

/*
 * This function contains 36 FP additions, 36 FP multiplications,
 * (or, 15 additions, 15 multiplications, 21 fused multiply/add),
 * 49 stack variables, and 14 memory accesses
 */
/*
 * Generator Id's : 
 * $Id: algsimp.ml,v 1.9 2006-02-12 23:34:12 athena Exp $
 * $Id: fft.ml,v 1.4 2006-01-05 03:04:27 stevenj Exp $
 * $Id: gen_twiddle_c.ml,v 1.14 2006-02-12 23:34:12 athena Exp $
 */

#include "fftw-spu.h"

const R *X(spu_t1fv_7) (R *ri, R *ii, const R *W, stride ios, INT m, INT dist) {
     DVK(KP900968867, +0.900968867902419126236102319507445051165919162);
     DVK(KP692021471, +0.692021471630095869627814897002069140197260599);
     DVK(KP801937735, +0.801937735804838252472204639014890102331838324);
     DVK(KP974927912, +0.974927912181823607018131682993931217232785801);
     DVK(KP554958132, +0.554958132087371191422194871006410481067288862);
     DVK(KP356895867, +0.356895867892209443894399510021300583399127187);
     INT i;
     R *x;
     x = ri;
     for (i = m; i > 0; i = i - VL, x = x + (VL * dist), W = W + (TWVL * 12), MAKE_VOLATILE_STRIDE(ios)) {
	  V T1, T6, Tl, Tm, Tg, Tb, Tn, Ti, Tz, Ts, To, TC, Tv, T3, T5;
	  V Tf, Td, Ta, T8, T2, T4, Te, Tc, T9, T7, Th, TD, TB, TA, TF;
	  V TE, Tp, Tk, Tj, Tr, Tq, Tw, Tu, Tt, Ty, Tx;
	  T1 = LD(&(x[0]), dist, &(x[0]));
	  T2 = LD(&(x[WS(ios, 1)]), dist, &(x[WS(ios, 1)]));
	  T3 = BYTWJ(&(W[0]), T2);
	  T4 = LD(&(x[WS(ios, 6)]), dist, &(x[0]));
	  T5 = BYTWJ(&(W[TWVL * 10]), T4);
	  Te = LD(&(x[WS(ios, 4)]), dist, &(x[0]));
	  Tf = BYTWJ(&(W[TWVL * 6]), Te);
	  Tc = LD(&(x[WS(ios, 3)]), dist, &(x[WS(ios, 1)]));
	  Td = BYTWJ(&(W[TWVL * 4]), Tc);
	  T9 = LD(&(x[WS(ios, 5)]), dist, &(x[WS(ios, 1)]));
	  Ta = BYTWJ(&(W[TWVL * 8]), T9);
	  T7 = LD(&(x[WS(ios, 2)]), dist, &(x[0]));
	  T8 = BYTWJ(&(W[TWVL * 2]), T7);
	  T6 = VADD(T3, T5);
	  Tl = VSUB(T5, T3);
	  Tm = VSUB(Tf, Td);
	  Tg = VADD(Td, Tf);
	  Tb = VADD(T8, Ta);
	  Tn = VSUB(Ta, T8);
	  Ti = VFNMS(LDK(KP356895867), T6, Tg);
	  Tz = VFNMS(LDK(KP356895867), Tg, Tb);
	  Ts = VFNMS(LDK(KP356895867), Tb, T6);
	  To = VFMA(LDK(KP554958132), Tn, Tm);
	  TC = VFNMS(LDK(KP554958132), Tl, Tn);
	  Tv = VFMA(LDK(KP554958132), Tm, Tl);
	  Th = VADD(T1, VADD(T6, VADD(Tb, Tg)));
	  ST(&(x[0]), Th, dist, &(x[0]));
	  TD = VMUL(LDK(KP974927912), VFNMS(LDK(KP801937735), TC, Tm));
	  TA = VFNMS(LDK(KP692021471), Tz, T6);
	  TB = VFNMS(LDK(KP900968867), TA, T1);
	  TF = VFMAI(TD, TB);
	  TE = VFNMSI(TD, TB);
	  ST(&(x[WS(ios, 4)]), TE, dist, &(x[0]));
	  ST(&(x[WS(ios, 3)]), TF, dist, &(x[WS(ios, 1)]));
	  Tp = VMUL(LDK(KP974927912), VFNMS(LDK(KP801937735), To, Tl));
	  Tj = VFNMS(LDK(KP692021471), Ti, Tb);
	  Tk = VFNMS(LDK(KP900968867), Tj, T1);
	  Tq = VFNMSI(Tp, Tk);
	  Tr = VFMAI(Tp, Tk);
	  ST(&(x[WS(ios, 5)]), Tq, dist, &(x[WS(ios, 1)]));
	  ST(&(x[WS(ios, 2)]), Tr, dist, &(x[0]));
	  Tw = VMUL(LDK(KP974927912), VFMA(LDK(KP801937735), Tv, Tn));
	  Tt = VFNMS(LDK(KP692021471), Ts, Tg);
	  Tu = VFNMS(LDK(KP900968867), Tt, T1);
	  Ty = VFMAI(Tw, Tu);
	  Tx = VFNMSI(Tw, Tu);
	  ST(&(x[WS(ios, 6)]), Tx, dist, &(x[0]));
	  ST(&(x[WS(ios, 1)]), Ty, dist, &(x[WS(ios, 1)]));
     }
     return W;
}
