/* Generated by: ../../genfft/gen_twiddle_c -standalone -fma -reorder-insns -simd -compact -variables 100000 -include fftw-spu.h -trivial-stores -n 8 -name X(spu_t1fv_8) */

/*
 * This function contains 33 FP additions, 24 FP multiplications,
 * (or, 23 additions, 14 multiplications, 10 fused multiply/add),
 * 44 stack variables, and 16 memory accesses
 */
/*
 * Generator Id's : 
 * $Id: algsimp.ml,v 1.9 2006-02-12 23:34:12 athena Exp $
 * $Id: fft.ml,v 1.4 2006-01-05 03:04:27 stevenj Exp $
 * $Id: gen_twiddle_c.ml,v 1.14 2006-02-12 23:34:12 athena Exp $
 */

#include "fftw-spu.h"

const R *X(spu_t1fv_8) (R *ri, R *ii, const R *W, stride ios, INT m, INT dist) {
     DVK(KP707106781, +0.707106781186547524400844362104849039284835938);
     INT i;
     R *x;
     x = ri;
     for (i = m; i > 0; i = i - VL, x = x + (VL * dist), W = W + (TWVL * 14), MAKE_VOLATILE_STRIDE(ios)) {
	  V T4, Tu, Tl, Tv, Tx, Ty, Tf, Tm, T1, T3, T2, Ti, Tk, Th, Tj;
	  V T6, Td, T8, Tb, T5, Tc, T7, Ta, T9, Te, Tq, Tr, Tw, Tz, To;
	  V Tp, Tg, Tn, TE, TF, TC, TD, Ts, Tt, TA, TB;
	  T1 = LD(&(x[0]), dist, &(x[0]));
	  T2 = LD(&(x[WS(ios, 4)]), dist, &(x[0]));
	  T3 = BYTWJ(&(W[TWVL * 6]), T2);
	  T4 = VSUB(T1, T3);
	  Tu = VADD(T1, T3);
	  Th = LD(&(x[WS(ios, 2)]), dist, &(x[0]));
	  Ti = BYTWJ(&(W[TWVL * 2]), Th);
	  Tj = LD(&(x[WS(ios, 6)]), dist, &(x[0]));
	  Tk = BYTWJ(&(W[TWVL * 10]), Tj);
	  Tl = VSUB(Ti, Tk);
	  Tv = VADD(Ti, Tk);
	  T5 = LD(&(x[WS(ios, 1)]), dist, &(x[WS(ios, 1)]));
	  T6 = BYTWJ(&(W[0]), T5);
	  Tc = LD(&(x[WS(ios, 3)]), dist, &(x[WS(ios, 1)]));
	  Td = BYTWJ(&(W[TWVL * 4]), Tc);
	  T7 = LD(&(x[WS(ios, 5)]), dist, &(x[WS(ios, 1)]));
	  T8 = BYTWJ(&(W[TWVL * 8]), T7);
	  Ta = LD(&(x[WS(ios, 7)]), dist, &(x[WS(ios, 1)]));
	  Tb = BYTWJ(&(W[TWVL * 12]), Ta);
	  Tx = VADD(T6, T8);
	  T9 = VSUB(T6, T8);
	  Te = VSUB(Tb, Td);
	  Ty = VADD(Tb, Td);
	  Tf = VADD(T9, Te);
	  Tm = VSUB(Te, T9);
	  Tg = VFMA(LDK(KP707106781), Tf, T4);
	  Tq = VFNMS(LDK(KP707106781), Tf, T4);
	  Tr = VFMA(LDK(KP707106781), Tm, Tl);
	  Tn = VFNMS(LDK(KP707106781), Tm, Tl);
	  To = VFNMSI(Tn, Tg);
	  Tp = VFMAI(Tn, Tg);
	  ST(&(x[WS(ios, 1)]), To, dist, &(x[WS(ios, 1)]));
	  ST(&(x[WS(ios, 7)]), Tp, dist, &(x[WS(ios, 1)]));
	  TC = VSUB(Tu, Tv);
	  Tw = VADD(Tu, Tv);
	  Tz = VADD(Tx, Ty);
	  TD = VSUB(Ty, Tx);
	  TE = VFNMSI(TD, TC);
	  TF = VFMAI(TD, TC);
	  ST(&(x[WS(ios, 6)]), TE, dist, &(x[0]));
	  ST(&(x[WS(ios, 2)]), TF, dist, &(x[0]));
	  Ts = VFNMSI(Tr, Tq);
	  Tt = VFMAI(Tr, Tq);
	  ST(&(x[WS(ios, 5)]), Ts, dist, &(x[WS(ios, 1)]));
	  ST(&(x[WS(ios, 3)]), Tt, dist, &(x[WS(ios, 1)]));
	  TA = VSUB(Tw, Tz);
	  TB = VADD(Tw, Tz);
	  ST(&(x[WS(ios, 4)]), TA, dist, &(x[0]));
	  ST(&(x[0]), TB, dist, &(x[0]));
     }
     return W;
}
