/* Generated by: ../../genfft/gen_twiddle_c -standalone -fma -reorder-insns -simd -compact -variables 100000 -include fftw-spu.h -trivial-stores -n 6 -name X(spu_t1fv_6) */

/*
 * This function contains 23 FP additions, 18 FP multiplications,
 * (or, 17 additions, 12 multiplications, 6 fused multiply/add),
 * 33 stack variables, and 12 memory accesses
 */
/*
 * Generator Id's : 
 * $Id: algsimp.ml,v 1.9 2006-02-12 23:34:12 athena Exp $
 * $Id: fft.ml,v 1.4 2006-01-05 03:04:27 stevenj Exp $
 * $Id: gen_twiddle_c.ml,v 1.14 2006-02-12 23:34:12 athena Exp $
 */

#include "fftw-spu.h"

const R *X(spu_t1fv_6) (R *ri, R *ii, const R *W, stride ios, INT m, INT dist) {
     DVK(KP500000000, +0.500000000000000000000000000000000000000000000);
     DVK(KP866025403, +0.866025403784438646763723170752936183471402627);
     INT i;
     R *x;
     x = ri;
     for (i = m; i > 0; i = i - VL, x = x + (VL * dist), W = W + (TWVL * 10), MAKE_VOLATILE_STRIDE(ios)) {
	  V T4, Tl, Tf, Ti, Tr, To, T1, T3, T2, T6, Td, T8, Tb, T5, Tc;
	  V T7, Ta, Tm, Tn, T9, Te, Th, Tq, Tg, Tp, Tj, Tk, Ts, Tt;
	  T1 = LD(&(x[0]), dist, &(x[0]));
	  T2 = LD(&(x[WS(ios, 3)]), dist, &(x[WS(ios, 1)]));
	  T3 = BYTWJ(&(W[TWVL * 4]), T2);
	  T4 = VSUB(T1, T3);
	  Tl = VADD(T1, T3);
	  T5 = LD(&(x[WS(ios, 2)]), dist, &(x[0]));
	  T6 = BYTWJ(&(W[TWVL * 2]), T5);
	  Tc = LD(&(x[WS(ios, 1)]), dist, &(x[WS(ios, 1)]));
	  Td = BYTWJ(&(W[0]), Tc);
	  T7 = LD(&(x[WS(ios, 5)]), dist, &(x[WS(ios, 1)]));
	  T8 = BYTWJ(&(W[TWVL * 8]), T7);
	  Ta = LD(&(x[WS(ios, 4)]), dist, &(x[0]));
	  Tb = BYTWJ(&(W[TWVL * 6]), Ta);
	  T9 = VSUB(T6, T8);
	  Tm = VADD(T6, T8);
	  Tn = VADD(Tb, Td);
	  Te = VSUB(Tb, Td);
	  Tf = VADD(T9, Te);
	  Ti = VMUL(LDK(KP866025403), VSUB(Te, T9));
	  Tr = VMUL(LDK(KP866025403), VSUB(Tn, Tm));
	  To = VADD(Tm, Tn);
	  Tg = VADD(T4, Tf);
	  Th = VFNMS(LDK(KP500000000), Tf, T4);
	  ST(&(x[WS(ios, 3)]), Tg, dist, &(x[WS(ios, 1)]));
	  Tp = VADD(Tl, To);
	  Tq = VFNMS(LDK(KP500000000), To, Tl);
	  ST(&(x[0]), Tp, dist, &(x[0]));
	  Tj = VFNMSI(Ti, Th);
	  Tk = VFMAI(Ti, Th);
	  ST(&(x[WS(ios, 5)]), Tj, dist, &(x[WS(ios, 1)]));
	  ST(&(x[WS(ios, 1)]), Tk, dist, &(x[WS(ios, 1)]));
	  Ts = VFNMSI(Tr, Tq);
	  Tt = VFMAI(Tr, Tq);
	  ST(&(x[WS(ios, 2)]), Ts, dist, &(x[0]));
	  ST(&(x[WS(ios, 4)]), Tt, dist, &(x[0]));
     }
     return W;
}
