/* Generated by: ../../genfft/gen_twiddle_c -standalone -fma -reorder-insns -simd -compact -variables 100000 -include fftw-spu.h -trivial-stores -n 5 -name X(spu_t1fv_5) */

/*
 * This function contains 20 FP additions, 19 FP multiplications,
 * (or, 11 additions, 10 multiplications, 9 fused multiply/add),
 * 31 stack variables, and 10 memory accesses
 */
/*
 * Generator Id's : 
 * $Id: algsimp.ml,v 1.9 2006-02-12 23:34:12 athena Exp $
 * $Id: fft.ml,v 1.4 2006-01-05 03:04:27 stevenj Exp $
 * $Id: gen_twiddle_c.ml,v 1.14 2006-02-12 23:34:12 athena Exp $
 */

#include "fftw-spu.h"

const R *X(spu_t1fv_5) (R *ri, R *ii, const R *W, stride ios, INT m, INT dist) {
     DVK(KP559016994, +0.559016994374947424102293417182819058860154590);
     DVK(KP618033988, +0.618033988749894848204586834365638117720309180);
     DVK(KP951056516, +0.951056516295153572116439333379382143405698634);
     DVK(KP250000000, +0.250000000000000000000000000000000000000000000);
     INT i;
     R *x;
     x = ri;
     for (i = m; i > 0; i = i - VL, x = x + (VL * dist), W = W + (TWVL * 8), MAKE_VOLATILE_STRIDE(ios)) {
	  V T1, Tg, Th, Tc, Te, T3, Ta, T5, T8, T2, T9, T4, T7, T6, Tb;
	  V Td, Tp, Ti, Tm, Tl, Tf, Tk, Tn, Tj, To;
	  T1 = LD(&(x[0]), dist, &(x[0]));
	  T2 = LD(&(x[WS(ios, 1)]), dist, &(x[WS(ios, 1)]));
	  T3 = BYTWJ(&(W[0]), T2);
	  T9 = LD(&(x[WS(ios, 3)]), dist, &(x[WS(ios, 1)]));
	  Ta = BYTWJ(&(W[TWVL * 4]), T9);
	  T4 = LD(&(x[WS(ios, 4)]), dist, &(x[0]));
	  T5 = BYTWJ(&(W[TWVL * 6]), T4);
	  T7 = LD(&(x[WS(ios, 2)]), dist, &(x[0]));
	  T8 = BYTWJ(&(W[TWVL * 2]), T7);
	  Tg = VSUB(T3, T5);
	  T6 = VADD(T3, T5);
	  Tb = VADD(T8, Ta);
	  Th = VSUB(T8, Ta);
	  Tc = VADD(T6, Tb);
	  Te = VSUB(T6, Tb);
	  Tp = VADD(T1, Tc);
	  Td = VFNMS(LDK(KP250000000), Tc, T1);
	  ST(&(x[0]), Tp, dist, &(x[0]));
	  Ti = VMUL(LDK(KP951056516), VFMA(LDK(KP618033988), Th, Tg));
	  Tm = VMUL(LDK(KP951056516), VFNMS(LDK(KP618033988), Tg, Th));
	  Tl = VFNMS(LDK(KP559016994), Te, Td);
	  Tf = VFMA(LDK(KP559016994), Te, Td);
	  Tk = VFMAI(Ti, Tf);
	  Tj = VFNMSI(Ti, Tf);
	  ST(&(x[WS(ios, 1)]), Tj, dist, &(x[WS(ios, 1)]));
	  Tn = VFMAI(Tm, Tl);
	  To = VFNMSI(Tm, Tl);
	  ST(&(x[WS(ios, 3)]), To, dist, &(x[WS(ios, 1)]));
	  ST(&(x[WS(ios, 4)]), Tk, dist, &(x[0]));
	  ST(&(x[WS(ios, 2)]), Tn, dist, &(x[0]));
     }
     return W;
}
