find_library(FOUND_FFTW_M_LIB m DOC "Math library")
if(NOT FOUND_FFTW_M_LIB STREQUAL "FOUND_FFTW_M_LIB-NOTFOUND")
  set(FFTW_M_LIB ${FOUND_FFTW_M_LIB})
  message(STATUS "Use m lib : ${FFTW_M_LIB}")
  set(FTTW_HAVE_M_LIB YES)
endif()

include(CheckIncludeFile)
include(CheckSymbolExists)
include(CheckFunctionExists)
include(CheckTypeSize)

set(DISABLE_FORTRAN 1)

# check required system includes

CHECK_INCLUDE_FILE(alloca.h HAVE_ALLOCA_H)
CHECK_INCLUDE_FILE(altivec.h HAVE_ALTIVEC_H)

CHECK_INCLUDE_FILE(strings.h HAVE_STRINGS_H)

CHECK_INCLUDE_FILE(sys/stat.h HAVE_SYS_STAT_H)
CHECK_INCLUDE_FILE(sys/sysctl.h HAVE_SYS_SYSCTL_H)
CHECK_INCLUDE_FILE(sys/time.h HAVE_SYS_TIME_H)
CHECK_INCLUDE_FILE(sys/types.h HAVE_SYS_TYPES_H)
CHECK_INCLUDE_FILE(unistd.h HAVE_UNISTD_H)
CHECK_INCLUDE_FILE(c_asm.h HAVE_C_ASM_H)
CHECK_INCLUDE_FILE(dlfcn.h HAVE_DLFCN_H)
CHECK_INCLUDE_FILE(intrinsics.h HAVE_INTRINSICS_H)

CHECK_INCLUDE_FILE(libintl.h HAVE_LIBINTL_H)

CHECK_INCLUDE_FILE(mach/mach_time.h HAVE_MACH_MACH_TIME_H)
CHECK_INCLUDE_FILE(malloc.h HAVE_MALLOC_H)
CHECK_INCLUDE_FILE(memory.h HAVE_MEMORY_H)
CHECK_INCLUDE_FILE(math.h HAVE_MATH_H)


# check ANSI C headers
# C90/89
CHECK_INCLUDE_FILE(assert.h HAVE_ASSERT_H)
CHECK_INCLUDE_FILE(ctype.h  HAVE_CTYPE_H )
CHECK_INCLUDE_FILE(errno.h  HAVE_ERRNO_H )
CHECK_INCLUDE_FILE(float.h  HAVE_FLOAT_H )
CHECK_INCLUDE_FILE(limits.h HAVE_LIMITS_H)
CHECK_INCLUDE_FILE(locale.h HAVE_LOCALE_H)
CHECK_INCLUDE_FILE(math.h   HAVE_MATH_H  )
CHECK_INCLUDE_FILE(setjmp.h HAVE_SETJMP_H)
CHECK_INCLUDE_FILE(signal.h HAVE_SIGNAL_H)
CHECK_INCLUDE_FILE(stdarg.h HAVE_STDARG_H)
CHECK_INCLUDE_FILE(stddef.h HAVE_STDDEF_H)
CHECK_INCLUDE_FILE(stdio.h  HAVE_STDIO_H )
CHECK_INCLUDE_FILE(stdlib.h HAVE_STDLIB_H)
CHECK_INCLUDE_FILE(string.h HAVE_STRING_H)
CHECK_INCLUDE_FILE(time.h   HAVE_TIME_H  )

if(HAVE_ASSERT_H AND
HAVE_CTYPE_H AND
HAVE_ERRNO_H AND
HAVE_FLOAT_H AND
HAVE_LIMITS_H AND
HAVE_LOCALE_H AND
HAVE_MATH_H  AND
HAVE_SETJMP_H AND
HAVE_SIGNAL_H AND
HAVE_STDARG_H AND
HAVE_STDDEF_H AND
HAVE_STDIO_H  AND
HAVE_STDLIB_H AND
HAVE_STRING_H AND
HAVE_TIME_H  )
    set(STDC_HEADERS 1)
endif()

# C99
CHECK_INCLUDE_FILE(inttypes.h HAVE_INTTYPES_H)
CHECK_INCLUDE_FILE(stdint.h HAVE_STDINT_H)

# check required symbols/functions

if(HAVE_ALLOCA_H)
    CHECK_SYMBOL_EXISTS(alloca alloca.h HAVE_ALLOCA)
endif()

CHECK_SYMBOL_EXISTS(srand48 stdlib.h HAVE_DECL_SRAND48)
CHECK_SYMBOL_EXISTS(drand48 stdlib.h HAVE_DECL_DRAND48)

CHECK_FUNCTION_EXISTS(drand48 HAVE_DRAND48)

CHECK_FUNCTION_EXISTS(abort HAVE_ABORT_FUN)
CHECK_SYMBOL_EXISTS(abort stdlib.h HAVE_ABORT_DECL)

CHECK_FUNCTION_EXISTS(sysctl HAVE_SYSCTL)

if(HAVE_ABORT_FUN AND HAVE_ABORT_DECL)
    set(HAVE_ABORT 1)
endif()

if(FFTW_HAVE_M_LIB)
  set(CMAKE_REQUIRED_LIBRARIES m)
endif()
if(HAVE_MATH_H)
    CHECK_SYMBOL_EXISTS(cosl math.h HAVE_DECL_COSL)
    CHECK_FUNCTION_EXISTS(cosl HAVE_COSL)
    CHECK_SYMBOL_EXISTS(cosq math.h HAVE_DECL_COSQ)
    CHECK_SYMBOL_EXISTS(sinq math.h HAVE_DECL_SINQ)
    CHECK_SYMBOL_EXISTS(sinl math.h HAVE_DECL_SINL)
    CHECK_FUNCTION_EXISTS(sinl HAVE_SINL)
    CHECK_FUNCTION_EXISTS(tanl HAVE_TANL)
    CHECK_SYMBOL_EXISTS(isnan math.h HAVE_ISNAN)
    CHECK_SYMBOL_EXISTS(sqrt math.h HAVE_SQRT_DECL_IN_MATH_H)

    if(HAVE_SQRT_DECL_IN_MATH_H)
        CHECK_FUNCTION_EXISTS(sqrt HAVE_SQRT)
    endif()
endif()
unset(CMAKE_REQUIRED_LIBRARIES)

CHECK_SYMBOL_EXISTS(gethrtime sys/time.h HAVE_GETHRTIME)
CHECK_SYMBOL_EXISTS(gettimeofday sys/time.h HAVE_GETTIMEOFDAY)
CHECK_SYMBOL_EXISTS(hrtime_t sys/time.h HAVE_HRTIME_T)
CHECK_SYMBOL_EXISTS(BSDgettimeofday sys/time.h HAVE_BSDGETTIMEOFDAY)

CHECK_SYMBOL_EXISTS(clock_gettime time.h HAVE_CLOCK_GETTIME)

CHECK_SYMBOL_EXISTS(posix_memalign stdlib.h HAVE_DECL_POSIX_MEMALIGN)
CHECK_SYMBOL_EXISTS(memalign malloc.h HAVE_DECL_MEMALIGN)

CHECK_FUNCTION_EXISTS(posix_memalign HAVE_POSIX_MEMALIGN)
CHECK_FUNCTION_EXISTS(memalign HAVE_MEMALIGN)


if(HAVE_STRING_H)
    CHECK_SYMBOL_EXISTS(memset string.h HAVE_MEMSET)
endif()

if(HAVE_MACH_MACH_TIME_H)
    CHECK_SYMBOL_EXISTS(mach_absolute_time mach/mach_time.h HAVE_MACH_ABSOLUTE_TIME)
endif()

CHECK_SYMBOL_EXISTS(read_real_time sys/time.h;sys/systemcfg.h HAVE_READ_REAL_TIME)
CHECK_SYMBOL_EXISTS(time_base_to_time sys/time.h;sys/systemcfg.h HAVE_TIME_BASE_TO_TIME)

CHECK_SYMBOL_EXISTS(uintptr_t stdint.h HAVE_UINTPTR_T)

CHECK_FUNCTION_EXISTS(snprintf HAVE_SNPRINTF)


CHECK_FUNCTION_EXISTS(vprintf HAVE_VPRINTF)
if(NOT HAVE_VPRINTF)
    CHECK_FUNCTION_EXISTS(_doprnt HAVE_DOPRNT)
endif()

CHECK_FUNCTION_EXISTS(_mm_free HAVE__MM_FREE)
CHECK_FUNCTION_EXISTS(_mm_malloc HAVE__MM_MALLOC)



#FIXME : check size
#set(CMAKE_EXTRA_INCLUDE_FILES ${CMAKE_CURRENT_SOURCE_DIR}/api/fftw3.h)
#check_type_size("fftw_r2r_kind_do_not_use_me" SIZEOF_FFTW_R2R_KIND)

CHECK_TYPE_SIZE("long double" SIZEOF_LONG_DOUBLE)
CHECK_TYPE_SIZE("float" SIZEOF_FLOAT)
CHECK_TYPE_SIZE("double" SIZEOF_DOUBLE)
CHECK_TYPE_SIZE("int" SIZEOF_INT)
CHECK_TYPE_SIZE("long" SIZEOF_LONG)
CHECK_TYPE_SIZE("long long" SIZEOF_LONG_LONG)
CHECK_TYPE_SIZE("MPI_Fint" SIZEOF_MPI_FINT)
CHECK_TYPE_SIZE("ptrdiff_t" SIZEOF_PTRDIFF_T)
CHECK_TYPE_SIZE("size_t" SIZEOF_SIZE_T)
CHECK_TYPE_SIZE("unsigned int" SIZEOF_UNSIGNED_INT)
CHECK_TYPE_SIZE("unsigned long" SIZEOF_UNSIGNED_LONG)
CHECK_TYPE_SIZE("unsigned long long" SIZEOF_UNSIGNED_LONG_LONG)
CHECK_TYPE_SIZE("void*" SIZEOF_VOID_P)

if(HAVE_SIZEOF_LONG_DOUBLE)
    set(HAVE_LONG_DOUBLE 1)
endif()
